services:
  db:
    ports:
      - "5432:5432"

  db_test:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: bookstore_test
    tmpfs: /var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "test", "-d", "bookstore_test"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      target: dev
    environment:
      DATABASE_TEST_URL: postgres://test:test@db_test:5432/bookstore_test
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      db_test:
        condition: service_healthy
